### ISSUE TITLE
win端安装的出现此项错误：“由于目标计算机积极拒绝，无法连接。”，请问如何解决？

### ISSUE THREAD

**Issue by conan257** [HenryXiaoYang/XYBot#58]
win10客户端
微信，Python安装的都是教程提供的版本

PS C:\Users\Administrator\Desktop\XYBot> python start.py
2024-07-28 23:25:31.941 | INFO     | utils.database:__init__:37 - [数据库]检测数据库是否有正确的列
2024-07-28 23:25:31.956 | INFO     | __main__:main:65 - 已设置日志
2024-07-28 23:25:31.966 | INFO     | __main__:main:76 - 读取设置成功
2024-07-28 23:25:31.966 | INFO     | __main__:main:81 - 机器人实例化成功
2024-07-28 23:25:31.966 | INFO     | __main__:main:84 - 开始注入Hook
2024-07-28 23:25:32.687 | DEBUG    | pywxdll.pywxdll:windows_start_wechat_inject_and_fix_ver:79 - 0,6536
2024-07-28 23:25:32.687 | INFO     | __main__:main:102 - 已注入微信Hook
2024-07-28 23:25:32.687 | INFO     | __main__:main:127 - 开始检测微信是否登陆
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 495, in _make_request
    conn.request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 398, in request
    self.endheaders()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1007, in _send_output
    self.send(msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 947, in send
    self.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 236, in connect
    self.sock = self._new_conn()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002295C03BD30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积 极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=19088): Max retries exceeded with url: /api/checkLogin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002295C03BD30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 172, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "start.py", line 128, in main
    if not bot.is_logged_in():
  File "C:\Users\Administrator\Desktop\XYBot\pywxdll\pywxdll.py", line 115, in is_logged_in
    json_response = self.raw_is_logged_in()
  File "C:\Users\Administrator\Desktop\XYBot\pywxdll\pywxdll.py", line 107, in raw_is_logged_in
    response = requests.post(url, data=json_para)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=19088): Max retries exceeded with url: /api/checkLogin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002295C03BD30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by 2468309202** [comment]
我也是同样的问题，启动一下就不行了

**Comment by HenryXiaoYang** [comment]
启动时微信有没有自动启动

**Comment by scc897577** [comment]
同样win，启动时微信有自动启动，但是如上两位所发的报错以后，微信就自动推出了。

**Comment by wacardTg** [comment]
有人解决了么？

**Comment by HenryXiaoYang** [comment]
这个错误能复刻出来吗，我这里死活弄不出这个错误。
我猜测是hook注入失败了。

**Comment by Jerry9666** [comment]
我也遇到一样的问题，我的解决方法是用管理员身份去启动cmd或者powershell，亲测有效

**Comment by HenryXiaoYang** [comment]
遇到这个问题的请检查一下python版本是否为64位3.8.10，微信版本是否为3.9.5.81。如果还不行就在这个issue下面反馈一下，发一下日志，最好有启动时的录屏，我好找问题。

**Comment by HenryXiaoYang** [comment]
我在我本地虚拟机新环境下能正常运行的，所以没找出问题在哪里。😭

**Comment by HenryXiaoYang** [comment]
好像找到什么问题了，请在运行前确保微信是完全关闭的状态。
