### ISSUE TITLE
运行start显示远程主机强迫关闭了一个链接

### ISSUE THREAD

**Issue by 3407712340** [HenryXiaoYang/XYBot#59]
<img width="713" alt="Snipaste_2024-08-03_17-09-13" src="https://github.com/user-attachments/assets/f8f721a9-d18b-401c-ac11-35cdc04c1638">

**Comment by HenryXiaoYang** [comment]
发下完整日志

**Comment by lopins** [comment]
> 发下完整日志
```
加载个人及系统配置文件用了 1255 毫秒。
(base) PS C:\Users\Administrator> cd E:/DevOps/Python/wechat/XYBot
(base) PS E:\DevOps\Python\wechat\XYBot> python start.py
2024-08-16 20:52:12.983 | WARNING  | utils.database:__init__:21 - 检测到数据库不存在，正在创建数据库
2024-08-16 20:52:12.994 | WARNING  | utils.database:__init__:30 - 已创建数据库
2024-08-16 20:52:12.994 | INFO     | utils.database:__init__:37 - [数据库]检测数据库是否有正确的列
2024-08-16 20:52:13.010 | INFO     | __main__:main:65 - 已设置日志
2024-08-16 20:52:13.013 | INFO     | __main__:main:76 - 读取设置成功
2024-08-16 20:52:13.013 | INFO     | __main__:main:81 - 机器人实例化成功
2024-08-16 20:52:13.013 | INFO     | __main__:main:84 - 开始注入Hook
2024-08-16 20:52:14.507 | DEBUG    | pywxdll.pywxdll:windows_start_wechat_inject_and_fix_ver:79 - 0,10820
2024-08-16 20:52:14.507 | INFO     | __main__:main:102 - 已注入微信Hook
2024-08-16 20:52:14.507 | INFO     | __main__:main:127 - 开始检测微信是否登陆
Traceback (most recent call last):
  File "D:\Python\Miniconda\Lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\Python\Miniconda\Lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\http\client.py", line 1428, in getresponse
    response.begin()
  File "D:\Python\Miniconda\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\http\client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\socket.py", line 708, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Miniconda\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\site-packages\urllib3\connectionpool.py", line 801, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\site-packages\urllib3\util\retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "D:\Python\Miniconda\Lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\Python\Miniconda\Lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\http\client.py", line 1428, in getresponse
    response.begin()
  File "D:\Python\Miniconda\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\http\client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\socket.py", line 708, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DevOps\Python\wechat\XYBot\start.py", line 172, in <module>
    asyncio.run(main())
  File "D:\Python\Miniconda\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\DevOps\Python\wechat\XYBot\start.py", line 128, in main
    if not bot.is_logged_in():
           ^^^^^^^^^^^^^^^^^^
  File "E:\DevOps\Python\wechat\XYBot\pywxdll\pywxdll.py", line 115, in is_logged_in
    json_response = self.raw_is_logged_in()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\DevOps\Python\wechat\XYBot\pywxdll\pywxdll.py", line 107, in raw_is_logged_in
    response = requests.post(url, data=json_para)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Miniconda\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
(base) PS E:\DevOps\Python\wechat\XYBot>
```

main_config.yml 文件已配置

**Comment by lopins** [comment]
> > 发下完整日志
> 
> ```
> 加载个人及系统配置文件用了 1255 毫秒。
> (base) PS C:\Users\Administrator> cd E:/DevOps/Python/wechat/XYBot
> (base) PS E:\DevOps\Python\wechat\XYBot> python start.py
> 2024-08-16 20:52:12.983 | WARNING  | utils.database:__init__:21 - 检测到数据库不存在，正在创建数据库
> 2024-08-16 20:52:12.994 | WARNING  | utils.database:__init__:30 - 已创建数据库
> 2024-08-16 20:52:12.994 | INFO     | utils.database:__init__:37 - [数据库]检测数据库是否有正确的列
> 2024-08-16 20:52:13.010 | INFO     | __main__:main:65 - 已设置日志
> 2024-08-16 20:52:13.013 | INFO     | __main__:main:76 - 读取设置成功
> 2024-08-16 20:52:13.013 | INFO     | __main__:main:81 - 机器人实例化成功
> 2024-08-16 20:52:13.013 | INFO     | __main__:main:84 - 开始注入Hook
> 2024-08-16 20:52:14.507 | DEBUG    | pywxdll.pywxdll:windows_start_wechat_inject_and_fix_ver:79 - 0,10820
> 2024-08-16 20:52:14.507 | INFO     | __main__:main:102 - 已注入微信Hook
> 2024-08-16 20:52:14.507 | INFO     | __main__:main:127 - 开始检测微信是否登陆
> Traceback (most recent call last):
>   File "D:\Python\Miniconda\Lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
>     httplib_response = self._make_request(
>                        ^^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "D:\Python\Miniconda\Lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
>     httplib_response = conn.getresponse()
>                        ^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\http\client.py", line 1428, in getresponse
>     response.begin()
>   File "D:\Python\Miniconda\Lib\http\client.py", line 331, in begin
>     version, status, reason = self._read_status()
>                               ^^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\http\client.py", line 292, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\socket.py", line 708, in readinto
>     return self._sock.recv_into(b)
>            ^^^^^^^^^^^^^^^^^^^^^^^
> ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Python\Miniconda\Lib\site-packages\requests\adapters.py", line 486, in send
>     resp = conn.urlopen(
>            ^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\site-packages\urllib3\connectionpool.py", line 801, in urlopen
>     retries = retries.increment(
>               ^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\site-packages\urllib3\util\retry.py", line 552, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\site-packages\urllib3\packages\six.py", line 769, in reraise
>     raise value.with_traceback(tb)
>   File "D:\Python\Miniconda\Lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
>     httplib_response = self._make_request(
>                        ^^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "D:\Python\Miniconda\Lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
>     httplib_response = conn.getresponse()
>                        ^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\http\client.py", line 1428, in getresponse
>     response.begin()
>   File "D:\Python\Miniconda\Lib\http\client.py", line 331, in begin
>     version, status, reason = self._read_status()
>                               ^^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\http\client.py", line 292, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\socket.py", line 708, in readinto
>     return self._sock.recv_into(b)
>            ^^^^^^^^^^^^^^^^^^^^^^^
> urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\DevOps\Python\wechat\XYBot\start.py", line 172, in <module>
>     asyncio.run(main())
>   File "D:\Python\Miniconda\Lib\asyncio\runners.py", line 194, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\asyncio\runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\asyncio\base_events.py", line 687, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "E:\DevOps\Python\wechat\XYBot\start.py", line 128, in main
>     if not bot.is_logged_in():
>            ^^^^^^^^^^^^^^^^^^
>   File "E:\DevOps\Python\wechat\XYBot\pywxdll\pywxdll.py", line 115, in is_logged_in
>     json_response = self.raw_is_logged_in()
>                     ^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\DevOps\Python\wechat\XYBot\pywxdll\pywxdll.py", line 107, in raw_is_logged_in
>     response = requests.post(url, data=json_para)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\site-packages\requests\api.py", line 115, in post
>     return request("post", url, data=data, json=json, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\site-packages\requests\api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\site-packages\requests\sessions.py", line 589, in request
>     resp = self.send(prep, **send_kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\site-packages\requests\sessions.py", line 703, in send
>     r = adapter.send(request, **kwargs)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Python\Miniconda\Lib\site-packages\requests\adapters.py", line 501, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
> (base) PS E:\DevOps\Python\wechat\XYBot>
> ```
> 
> main_config.yml 文件已配置

![image](https://github.com/user-attachments/assets/e7b5c4b7-2015-4f9a-aa67-2f7632ac10eb)
![image](https://github.com/user-attachments/assets/7e3cefc4-f9eb-4141-9ca8-fceaf95b91e2)
![image](https://github.com/user-attachments/assets/8cc99812-cc1c-4129-85ef-dc3fb26f4fcd)
![image](https://github.com/user-attachments/assets/c1fbabfc-db90-4d1e-a9e7-5f371406d80f)

![image](https://github.com/user-attachments/assets/5463e496-76cb-4ef5-8850-530a9947b7af)

2024-08-16 21:30:29 | INFO | 已设置日志
2024-08-16 21:30:29 | INFO | 读取设置成功
2024-08-16 21:30:29 | INFO | 机器人实例化成功
2024-08-16 21:30:29 | INFO | 开始注入Hook
2024-08-16 21:30:31 | DEBUG | 0,25264
2024-08-16 21:30:31 | INFO | 已注入微信Hook
2024-08-16 21:30:44 | INFO | 开始检测微信是否登陆

大概是这几个地方识别不到

**Comment by HenryXiaoYang** [comment]
请在运行start.py前确保微信是完全关闭的状态。
